[workspace]
members = ["vscodeconfigurator", "vscodeconfigurator-lib"]
resolver = "2"

package.authors = [
    "Tim Small"
]
package.edition = "2024"
package.license-file = "LICENSE"
package.homepage = "https://github.com/Smalls1652/vscodeconfigurator-rs"
package.repository = "https://github.com/Smalls1652/vscodeconfigurator-rs"

[workspace.dependencies]
clap = { version = "4.5.37", features = ["derive", "string", "cargo"] }
clap_complete = { version = "4.5.47" }
crossterm = { version = "0.29.0", features = ["events"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
