# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true

# Modules
reorder_modules = true

# Comments
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true

# Functions
fn_params_layout = "Vertical"

# Structs
reorder_impl_items = true

# Misc
trailing_comma = "Never"
