# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  push:
    tags-ignore: [ 'v*.*.*', 'v*.*.*-*' ]
    paths-ignore: 
        - "README.md"
        - "LICENSE"
        - ".vscode/**"
        - ".github/dependabot.yml"
  pull_request:
    paths-ignore: 
        - "README.md"
        - "LICENSE"
        - ".vscode/**"
        - ".github/dependabot.yml"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package_name: [
          "./src/Configurator/"
        ]
    env:
      CARGO_TERM_COLOR: always
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build project
        run: cargo build --package ${{ matrix.package_name }} --verbose
