# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Configurator / Create artifacts
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  workflow_dispatch:

permissions:
    packages: read

jobs:
    create-artifacts:
        name: Create artifacts
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest, windows-latest, macos-14 ]
        env:
            DOTNET_NOLOGO: true
        
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Setup Rust
            uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              toolchain: nightly

          # Install targets for Rust
          - name: Install targets (Windows)
            if: ${{ runner.os == 'Windows' }}
            shell: pwsh
            run: |
              rustup target add x86_64-pc-windows-gnu

          - name: Install targets (macOS)
            if: ${{ runner.os == 'macOS' }}
            shell: pwsh
            run: |
              rustup target add x86_64-apple-darwin;
              rustup target add aarch64-apple-darwin;

          - name: Install targets (Linux)
            if: ${{ runner.os == 'Linux' }}
            shell: pwsh
            run: |
              rustup target add x86_64-unknown-linux-gnu

          # Compile
          - name: Compile package (Windows)
            if: ${{ runner.os == 'Windows' }}
            shell: pwsh
            run: |
              ./tools/Compile-VSCodeConfigurator.ps1 -Platform "Windows" -Architecture "x64";

          - name: Compile package (macOS)
            if: ${{ runner.os == 'macOS' }}
            shell: pwsh
            run: |
              ./tools/Compile-VSCodeConfigurator.ps1 -Platform "macOS" -Architecture "x64";
              ./tools/Compile-VSCodeConfigurator.ps1 -Platform "macOS" -Architecture "arm64"

          - name: Compile package (Linux)
            if: ${{ runner.os == 'Linux' }}
            shell: pwsh
            run: |
              ./tools/Compile-VSCodeConfigurator.ps1 -Platform "Linux" -Architecture "x64";

          # Upload artifacts
          - name: Create artifact (Windows)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'Windows' }}
            with:
              name: "Configurator_win-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/windows-x64/**/*
              if-no-files-found: error

          - name: Create artifact (Linux - x64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'Linux' }}
            with:
              name: "Configurator_linux-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/linux-x64/**/*
              if-no-files-found: error

          - name: Create artifact (macOS - x64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'macOS' }}
            with:
              name: "Configurator_osx-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/macos-x64/**/*
              if-no-files-found: error

          - name: Create artifact (macOS - arm64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'macOS' }}
            with:
              name: "Configurator_osx-arm64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/macos-arm64/**/*
              if-no-files-found: error
