# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Configurator / Create artifacts
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  workflow_dispatch:

permissions:
    packages: read

jobs:
    create-artifacts:
        name: Create artifacts
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest, windows-latest, macos-14 ]
        env:
            DOTNET_NOLOGO: true
        
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          # Install targets for Rust
          - name: Install targets (Windows)
            if: ${{ runner.os == 'Windows' }}
            shell: pwsh
            run: |
              rustup target add x86_64-pc-windows-gnu

          - name: Install targets (macOS)
            if: ${{ runner.os == 'macOS' }}
            shell: pwsh
            run: |
              rustup target add x86_64-apple-darwin;
              rustup target add aarch64-apple-darwin;

          - name: Install targets (Linux)
            if: ${{ runner.os == 'Linux' }}
            shell: pwsh
            run: |
              rustup target add x86_64-unknown-linux-gnu;
              rustup target add aarch64-unknown-linux-gnu;

          # Compile
          - name: Compile package (Windows)
            if: ${{ runner.os == 'Windows' }}
            shell: pwsh
            run: |
              cargo build --release --package vscodeconfigurator --target x86_64-pc-windows-gnu;
              Copy-Item -Path "./target/x86_64-pc-windows-gnu/release/templates" -Destination "./artifacts/x86_64-pc-windows-gnu/" -Recurse -Force;
              Copy-Item -Path "./target/x86_64-pc-windows-gnu/release/vscodeconfigurator.exe" -Destination "./artifacts/x86_64-pc-windows-gnu/" -Force;

          - name: Compile package (macOS)
            if: ${{ runner.os == 'macOS' }}
            shell: pwsh
            run: |
              cargo build --release --package vscodeconfigurator --target x86_64-apple-darwin;
              Copy-Item -Path "./target/x86_64-apple-darwin/release/templates" -Destination "./artifacts/x86_64-apple-darwin/" -Recurse -Force;
              Copy-Item -Path "./target/x86_64-apple-darwin/release/vscodeconfigurator" -Destination "./artifacts/x86_64-apple-darwin/" -Force;
              cargo build --release --package vscodeconfigurator --target aarch64-apple-darwin;
              Copy-Item -Path "./target/aarch64-apple-darwin/release/templates" -Destination "./artifacts/aarch64-apple-darwin/" -Recurse -Force;
              Copy-Item -Path "./target/aarch64-apple-darwin/release/vscodeconfigurator" -Destination "./artifacts/aarch64-apple-darwin/" -Force;

          - name: Compile package (Linux)
            if: ${{ runner.os == 'Linux' }}
            shell: pwsh
            run: |
              cargo build --release --package vscodeconfigurator --target x86_64-unknown-linux-gnu;
              Copy-Item -Path "./target/x86_64-unknown-linux-gnu/release/templates" -Destination "./artifacts/x86_64-unknown-linux-gnu/" -Recurse -Force;
              Copy-Item -Path "./target/x86_64-unknown-linux-gnu/release/vscodeconfigurator" -Destination "./artifacts/x86_64-unknown-linux-gnu/" -Force;
              cargo build --release --package vscodeconfigurator --target aarch64-unknown-linux-gnu;
              Copy-Item -Path "./target/aarch64-unknown-linux-gnu/release/templates" -Destination "./artifacts/aarch64-unknown-linux-gnu/" -Recurse -Force;
              Copy-Item -Path "./target/aarch64-unknown-linux-gnu/release/vscodeconfigurator" -Destination "./artifacts/aarch64-unknown-linux-gnu/" -Force;

          # Upload artifacts
          - name: Create artifact (Windows)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'Windows' }}
            with:
              name: "Configurator_win-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/x86_64-pc-windows-gnu/**/*
              if-no-files-found: error

          - name: Create artifact (Linux - x64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'Linux' }}
            with:
              name: "Configurator_linux-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/x86_64-unknown-linux-gnu/**/*
              if-no-files-found: error

          - name: Create artifact (Linux - arm64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'Linux' }}
            with:
              name: "Configurator_linux-arm64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/aarch64-unknown-linux-gnu/**/*
              if-no-files-found: error

          - name: Create artifact (macOS - x64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'macOS' }}
            with:
              name: "Configurator_osx-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/x86_64-apple-darwin/**/*
              if-no-files-found: error

          - name: Create artifact (macOS - arm64)
            uses: actions/upload-artifact@v4
            if: ${{ runner.os == 'macOS' }}
            with:
              name: "Configurator_osx-arm64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
              path: ${{ github.workspace }}/artifacts/aarch64-apple-darwin/**/*
              if-no-files-found: error
